# Generated by Django 5.2.13 on 2026-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
